### ISSUE TITLE
`content_type.rs` example doesn't compile with current `mime` crate (0.3.5)

### ISSUE THREAD

**Issue by davechallis** [iron/iron#564]
Compiling the [content_type.rs](https://github.com/iron/iron/blob/master/examples/content_type.rs) currently fails when using the current latest version of the [mime](https://crates.io/crates/mime) crate (v0.3.5) and current latest Iron (v0.5.1).

Tested by compiling in a fresh module with cargo dependencies specified as:

    [dependencies]
    iron = "*"
    mime = "*"

This fails with:

    error: cannot find macro `mime!` in this scope
      --> src/main.rs:24:24
       |
    24 |     let content_type = mime!(Application/Json);
       |                        ^^^^

    error: aborting due to previous error

**Comment by phlmn** [comment]
Should be fixed by #523
