### ISSUE TITLE
Failing to build with latest rust nightly (0.13)

### ISSUE THREAD

**Issue by DominikGuzei** [iron/iron#233]
Hey there,
I just wanted to try out the iron framework but it fails to compile due to an API change to `std::rt::mutext::NativeMutex` used by the openssl2-sys crate.

This is the error:

```
error: unresolved import 'std::rt::mutex::NativeMutex'. Could not find 'mutex' in 'std::rt'.
```

Is there a way to fix openssl2-sys somehow?
